spring:
  application:
    name: dynamic-dataSource
  cloud:
    nacos:
      discovery:
        server-addr: 62.234.211.179:8848
        register-enabled: true
        namespace: ff361e46-bdc0-46c3-8ebe-1d545d4dedc4
  profiles:
    active: druids,hikaris
server:
  port: 10009
  tomcat:
    accept-count: 1000
    max-threads: 1000
logging:
  level.root: warn
  file:
    name: dynamic-dataSource.log
info:
  version: 1.0
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml