spring:
  application:
    name: admin-oo
  cloud:
    nacos:
      discovery:
        server-addr: 62.234.211.179:8848
        register-enabled: true
        namespace: ff361e46-bdc0-46c3-8ebe-1d545d4dedc4
server:
  port: 10010
  tomcat:
    accept-count: 1000
    max-threads: 200
logging:
  file:
    name: admin-oo.log
  level.root: warn
info:
  version: 1.0
management:
  endpoints:
    web:
      exposure:
        include: '*'