spring:
  application:
    name: learn-producer
  cloud:
    nacos:
      discovery:
        server-addr: 62.234.211.179:8848
        register-enabled: true
        namespace: ff361e46-bdc0-46c3-8ebe-1d545d4dedc4
  redis:
    host: 192.168.226.132
    port: 6379
  profiles:
    active: druid
server:
  port: 10001
  tomcat:
    accept-count: 1000
    max-threads: 1000
logging:
  level.root: warn
  file:
    name: learn-producer.log
info:
  version: 1.0
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  mapper-locations: classpath:mappers/**/*.xml