common:
  custom-durid:
    enabled: true
    driverClassName: com.mysql.cj.jdbc.Driver
    # 250
    url: jdbc:mysql://localhost:3306/component_learn?useSSL=false&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: zxx1994
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 50
    minIdle: 10
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: "SELECT 1 FROM DUAL"
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    filters: "stat,log4j"
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000