spring:
  application:
    name: services-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 62.234.211.179:8848
        register-enabled: true
        namespace: ff361e46-bdc0-46c3-8ebe-1d545d4dedc4
server:
  port: 10002
  tomcat:
    accept-count: 1000
    max-threads: 1000
logging:
  level.root: warn
  file:
    name: services-consumer.log
info:
  version: 1.0
management:
  endpoints:
    web:
      exposure:
        include: '*'